version: '3'

networks:
  touiteur.net:
    driver: bridge

services:
  php:
    hostname: interface-backend
    image: canals/php
    ports:
      - "20000:80"
    volumes:
      - ../public:/var/www/html
      - ../src:/var/www/src
    working_dir: /var/www/src
    networks:
      - touiteur.net
    depends_on:
      - sql

  sql:
    hostname: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=touiteur
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - "20001:3306"
    networks:
      - touiteur.net


  phpmyadmin:
    hostname: php-my-admin
    image: phpmyadmin
    environment:
      - PMA_HOST=sql
    ports:
      - "20002:80"
    networks:
      - touiteur.net
    depends_on:
      - sql

